version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .prodenv

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-prod
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .prodenv

  nginx:
    build:
      context: ./compose/nginx
      dockerfile: Dockerfile-prod
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:3.0

